### ISSUE TITLE
Love your library

### ISSUE THREAD

**Issue by dbergum** [cachapa/ExpandableLayout#12]
You should mention in your read me that if you're adding inflated views to the Expandable Layout programmatically you need to put the app:layout_expandable="true" attribute on the root view in your xml layout in order for it to work.

**Comment by cachapa** [comment]
ExpandableLinearLayout is deprecated partly because of the reason you mention (it's a bit more complex than necessary).

If you're still using ExpandableLinearLayout, I really recommend that you use ExpandableLayout instead. It has the exact same capabilities while being much more efficient and easy to use.
