### ISSUE TITLE
Can`t create ExpandableLinearLayout programmatically.

### ISSUE THREAD

**Issue by DemiN0u** [cachapa/ExpandableLayout#15]
I tried to create ExpandableLinearLayout programmatically but there is only one LayoutParams constructor `LayoutParams(Context c, AttributeSet attrs)`. 

Could you override other `LinearLayout.LayoutParams` constroctors without `AttributeSet` parametr?

**Comment by cachapa** [comment]
I see you're trying to use `ExpandableLinearLayout` which is deprecated.

I would strongly recommend that you use `ExpandableLayout` instead since it is much more efficient and fixes a few visual glitches during animation.
There's a demo that shows how to use the API.

I don't want to invest anymore time on `ExpandableLinearLayout` since it's deprecated, but If you want to create the constructor for its `LayoutParams` I'm willing to accept pull requests against it.

**Comment by DemiN0u** [comment]
I tried to use `ExpandableLayout` before but i haven`t fount how i can change expand orientation. If i create it programmatically I`ve got only horizontal expanding.

I think it happens beause I used constructor with context only and variable `orientation` wasn`t initialized at take 0 value.

Are there other  ways to set `orientation`?

**Comment by cachapa** [comment]
I see. I guess I wasn't really expecting anyone to create layouts programatically.

I'll add setters and getters analogous to the XML properties, I think that should be enough for what you need.

**Comment by cachapa** [comment]
You can try updating to 2.4
Let me know if there's anything missing.

**Comment by DemiN0u** [comment]
Works perfectly. Thanks.
