### ISSUE TITLE
BounceInterpolator only settle after the second click

### ISSUE THREAD

**Issue by powerhcm8** [cachapa/ExpandableLayout#20]
I am using Bounce Interpolator with the Expandable layout but when i expand i need to click at least two time for it close again. If i don't use any interpolator everything works like it should.
```
if (details.isExpanded()) {
    details.collapse();
    vPrecoComum.animate().alpha(1).start();
    details.animate().alpha(0).setDuration(300).start();
    expandButton.animate().rotation(0).start();
} else {
    details.expand();
    vPrecoComum.animate().alpha(0).start();
    details.animate().alpha(1).setDuration(300).start();
     expandButton.animate().rotation(180).start();
}
```

I tried debugging it end i saw that the expansion value is 1.0000545 on the first click.

**Comment by cachapa** [comment]
Thanks for the report. I managed to reproduce the problem and will post a fix asap.

On a side note: I would recommend you to use `OnExpansionUpdateListener` to apply the alpha and rotation animations rather than triggering them manually as you are doing in your code snippet.
This will work better in situations where the animation is cancelled for whatever reason.

It'd also allow you to use details.toggle() and remove the if clause altogether.

An example of how to use it is in https://github.com/cachapa/ExpandableLayout/blob/master/demo/src/main/java/net/cachapa/expandablelayoutdemo/HorizontalFragment.java#L33

**Comment by powerhcm8** [comment]
The problem of using  `OnExpansionUpdateListener` in this cause is that i also animate views outside ExpandableLayout, and they look weird with BounceInterpolator, but in other causes is great.
Is like they don't mix driving with alcohol and don't mix BounceInterpolator with Alpha.

**Comment by cachapa** [comment]
Oh yeah, good point I guess that would look weird!
