### ISSUE TITLE
animation in scroll view did not run properly

### ISSUE THREAD

**Issue by rajam1215** [cachapa/ExpandableLayout#22]
When i click the item of recycler view . the item go upside of screen and hide below toolbar. issue come in recycle srollbar. when click of item item that still stand at one place and except whole recycler view go upside of screen and hide behind the toolbar

**Comment by cachapa** [comment]
Sorry, but this issue tracker is meant for bug reports of feature requests specifically for the ExpandableLayout lib.
The problem you mention isn't caused by this library, but is rather a the more general problem of RecyclerView item visibility when the content changes.
For that type of support that please try http://stackoverflow.com

**Comment by rajam1215** [comment]
please give me any solution if u have
