### ISSUE TITLE
Collapse when the expandable layout is RecyclerView

### ISSUE THREAD

**Issue by chowaikong** [cachapa/ExpandableLayout#4]
It will auto collapse when the expandable layout is RecyclerView and it's WRAP_CONTENT, I have to add a parent layout to the RecyclerView and set minHeight to make sure the RecyclerView is visible.

**Comment by cachapa** [comment]
Can you show me the layout xml?

Does the code work if you use a simply LinearLayout instead of an ExpandableLinearLayout? I'm not sure RecyclerView is meant to be used with WRAP_CONTENT. Generally you'd use it with either MATCH_PARENT, a given weight, or a fixed height.

**Comment by chowaikong** [comment]
Here is XML that won't works:
<net.cachapa.expandablelayout.ExpandableLinearLayout
      android:id="@+id/expandable_layout"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:orientation="vertical"
      app:el_duration="300"
      app:el_expanded="false"
      >
      <TextView
          android:id="@+id/tv"
          android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:textSize="14sp"
          android:layout_gravity="center"
          android:gravity="center"
          />
      <android.support.v7.widget.RecyclerView
        android:id="@+id/rv"
        android:overScrollMode="never"
        android:padding="1dip"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_expandable="true"
        android:clipToPadding="false"
        android:orientation="vertical"
        />
  </net.cachapa.expandablelayout.ExpandableLinearLayout>

RecyclerView support WARP_CONTENT since 23.2.0 already.

**Comment by cachapa** [comment]
What happens if you set layout_expanded="true" in your RecyclerView?

Can you link me to the release notes where it says RecyclerView supports WRAP_CONTENT since 23.3.0?
My understanding was that the change was related to MATCH_PARENT in the item views. It still makes no sense to me for RecyclerView to support WRAP_CONTENT since its content are the items.
For the RV to wrap the content would mean it taking the height of the sum of it's items, essentially disabling scrolling and becoming a complex LinearLayout.

**Comment by chowaikong** [comment]
[http://android-developers.blogspot.hk/2016/02/android-support-library-232.html](url)
You can see RecyclerView support WARP_CONTENT in the link above, and I quote "This means that previously unavailable scenarios, such as using WRAP_CONTENT for a dimension of the RecyclerView, are now possible.".
I have simplify the code I post in the last comment, of course I have set layout_expanded="true" in RecyclerView in my production code.
Yes, my understanding is similar to yours, the expandable layout must set a fixed height or it will collapse the WRAP_CONTENT layout, so my suggestion is SUPPORT WRAP_CONTENT LAYOUT.

**Comment by cachapa** [comment]
You're right, WRAP_CONTENT should work in the newer versions of RV.

Did you edit your earlier post with the layout? I first saw it on my phone as text, but now it seems that it's a screenshot. I'm asking because now I'm not sure if I'm looking at the same layout file.

In any case, there are a few problems with your XML:
- You set el_expanded="false", which will cause the layout to start in the collapsed state.
- The above makes no difference since none of the child layouts are set as expandable="true".

I have tested a few variations of the issue from your earlier description in the included demo app, and couldn't replicate the problem.
Could you try replicating the problem in the demo? It's easier for me to fix the bug if I can replicate the problem here.

**Comment by chowaikong** [comment]
But wait, setting el_expanded="false" isn't in order to set the expandable layout collapsed by default?

**Comment by cachapa** [comment]
Yes. In your original report you said the layout was starting collapsed, that's why I mentioned it.

**Comment by chowaikong** [comment]
I found the reason for this problem, because I am using a custom RecyclerView called [SuperRecyclerView](https://github.com/Malinskiy/SuperRecyclerView), it's extends FrameLayout, so I wrap a fixed height LinearLayout with SuperRecyclerView works. RecyclerView from the support lib works fine in your demo, my requirement makes me have to use a custom RecyclerView.

**Comment by chowaikong** [comment]
So it maybe the problem is mine.

**Comment by cachapa** [comment]
Ok, thanks for clarifying
