### ISSUE TITLE
Skipped frames

### ISSUE THREAD

**Issue by pepela** [cachapa/ExpandableLayout#42]
The expand/collapse causes big frame skipping on Nexus 7 device when this layout is used in recycler view, but behaves seemingly on other devices. What might be the cause of such behavior?

**Comment by cachapa** [comment]
A layout pass is called on the parent layout for each frame of the expansion/collapse animation. This operation can be expensive if your parent layout is too complex (if it has too many children, or very complex views, such as a mapview or a webview).

If you're having problems with performance you can try simplifying your parent layout, or disabling the animation on older devices.

**Comment by pepela** [comment]
I don't think problem is with layout as same one works without problem on other devices (Pixel xl, Axon 7, galaxy s3) but has horrible performance on Nexus 7

**Comment by cachapa** [comment]
I assume you're talking about the original Nexus 7 which has horrible performance in general.
Honestly I don't think it's useful to spend much time optimizing code for very old devices, unless you have a lot of users with devices that are 5+ years old.

In any case this isn't a problem with ExpandableLayout. I've tried to make the expansion as efficient as possible, but the fact is that you need to perform a layout pass on the parent layout for each frame and that operation is inherently expensive on Android due to how the system is designed.

As I said above, if this is an important issue for you, you could try disabling animations on old devices.
