### ISSUE TITLE
can't save expanded item state when scroll recyclerview

### ISSUE THREAD

**Issue by shineM** [cachapa/ExpandableLayout#7]
the expanded item will collapse again when visible

**Comment by cachapa** [comment]
That's intended behaviour since the RecyclerView will reuse that view for another item and that item would then appear expanded, which is most likely not what you want.

You need to either save the expansion state somewhere and reset it on bind, or tell the RecyclerView not to recycle that specific item. There's a Google Dev blog post about that, but I can't look for it right now.
